# Generated by Django 2.2 on 2020-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
            ],
            options={
                'db_table': 'activity_period',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='User ID')),
                ('real_name', models.CharField(max_length=255, verbose_name='User Name')),
                ('tz', models.CharField(choices=[('P', 'America/Los_Angeles'), ('I', 'Asia/Kolkata')], max_length=255)),
                ('activity_period', models.ManyToManyField(to='assignment.ActivityPeriod')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
