# Generated by Django 2.2 on 2020-07-07 18:06

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=assignment.models.CustomDateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=assignment.models.CustomDateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=models.CharField(choices=[('America/Los_Angeles', 'America/Los_Angeles'), ('Asia/Kolkata', 'Asia/Kolkata')], max_length=255),
        ),
    ]
